apiVersion: v1
kind: Service
metadata:
    name: "atom-81db"
    labels:
        app: "atom-81db"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "atom-81db"