apiVersion: v1
kind: Service
metadata:
    name: "atomaks-b0f6"
    labels:
        app: "atomaks-b0f6"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "atomaks-b0f6"